import type { Application, Cause, LocationPoint, Opportunity, Profile } from "./types";

export const demoLocations: LocationPoint[] = [
  { place_id: "downtown-toronto", label: "Downtown Toronto, Ontario", address_line: "Downtown Toronto", locality: "Downtown Toronto", city: "Toronto", postcode: "M5H 2N2", country_code: "CA", latitude: 43.6532, longitude: -79.3832 },
  { place_id: "parkdale", label: "Parkdale, Toronto", address_line: "Parkdale", locality: "Parkdale", city: "Toronto", postcode: "M6K 2N6", country_code: "CA", latitude: 43.6405, longitude: -79.4369 },
  { place_id: "east-york", label: "East York, Toronto", address_line: "East York", locality: "East York", city: "Toronto", postcode: "M4W 3X8", country_code: "CA", latitude: 43.6841, longitude: -79.3654 },
  { place_id: "mississauga", label: "Mississauga, Ontario", address_line: "Mississauga", locality: "Mississauga", city: "Mississauga", postcode: "L5C 1E3", country_code: "CA", latitude: 43.589, longitude: -79.6441 },
  { place_id: "north-york", label: "North York, Toronto", address_line: "North York", locality: "North York", city: "Toronto", postcode: "M2N 5V7", country_code: "CA", latitude: 43.7615, longitude: -79.4111 },
];
export const causes: Cause[] = [
  { id: "cleanup", slug: "cleanup", name: "Cleanup" },
  { id: "planting", slug: "planting", name: "Planting" },
  { id: "monitoring", slug: "monitoring", name: "Monitoring" },
  { id: "community", slug: "community", name: "Community" },
];
const future = (days: number) => new Date(Date.now() + days * 86400000).toISOString();
const requirementDefaults = {
  is_accessible: true,
  eligibility_notes: "Open to volunteers who meet the listed minimum age.",
  time_commitment_minutes: 180,
  training_required: false,
  training_commitment: "A short briefing is provided at the meeting point.",
  screening_required: false,
  screening_steps: "No screening required.",
  transportation_info: "Public transport is available nearby; plan your own trip to the meeting point.",
  qualifications: "No prior qualifications required.",
  listing_source: "GiveHub organiser",
  listing_source_url: null,
  listing_verification_status: "verified" as const,
  source_updated_at: new Date().toISOString(),
  source_checked_at: new Date().toISOString(),
  application_mode: "internal" as const,
  external_application_url: null,
  updated_at: new Date().toISOString(),
};
export const opportunities: Opportunity[] = [
  {
    ...requirementDefaults,
    id: "beach-clean",
    title: "Woodbine Beach Cleanup",
    description: "Spend a purposeful morning restoring the shoreline with a friendly local crew.",
    impact_statement: "Leave one of Toronto’s busiest beaches better than you found it.",
    tasks: "Collect litter, sort recyclables, and record the most common waste items.",
    meeting_point: "Woodbine Beach boardwalk entrance",
    starts_at: future(5), ends_at: future(5), recurrence: "weekly", effort: "moderate",
    minimum_age: 14, accessibility: "Step-free meeting point; tasks can be adapted.",
    safety_notes: "Bring water, sun protection, and closed shoes.", capacity: 24, requires_waiver: true, confirmed_count: 18,
    image_url: "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=1200&q=85",
    status: "published", version: 1, organisation_name: "Toronto Community Action Network",
    location_label: "The Beaches, Toronto", address_line: "1675 Lake Shore Boulevard East", locality: "The Beaches", city: "Toronto", postcode: "M4L 3W6", country_code: "CA", latitude: 43.6621, longitude: -79.3094, location_visibility: "public",
    causes: [causes[0]!], distance_km: 1.7, is_saved: false,
  },
  {
    ...requirementDefaults,
    id: "garden-day", title: "Community Garden Planting Day",
    description: "Prepare garden beds and plant winter vegetables for the local food pantry.",
    impact_statement: "Grow fresh food that stays in the neighbourhood.",
    tasks: "Prepare soil, plant seedlings, mulch beds, and share refreshments.", meeting_point: "Masaryk Park community garden gate",
    starts_at: future(8), ends_at: future(8), recurrence: "monthly", effort: "active", minimum_age: 12,
    accessibility: "Wide paths and seated planting tasks are available.", safety_notes: "Gloves and tools are provided.", capacity: 18, requires_waiver: true, confirmed_count: 11,
    image_url: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1200&q=85",
    status: "published", version: 1, organisation_name: "Parkdale Community Pantry",
    location_label: "Parkdale, Toronto", address_line: "220 Cowan Avenue", locality: "Parkdale", city: "Toronto", postcode: "M6K 2N6", country_code: "CA", latitude: 43.6405, longitude: -79.4369, location_visibility: "public",
    causes: [causes[1]!], distance_km: 2.7, is_saved: true,
  },
  {
    ...requirementDefaults,
    is_accessible: false,
    training_required: true,
    training_commitment: "Complete a 45-minute field methods briefing before your first session.",
    id: "stream-watch", title: "Don River Water Quality Monitoring",
    description: "Measure stream health and identify freshwater species with trained coordinators.",
    impact_statement: "Build the evidence needed to protect an urban waterway.", tasks: "Take water readings, photograph sites, and log observations.",
    meeting_point: "Evergreen Brick Works welcome centre", starts_at: future(11), ends_at: future(11), recurrence: "monthly", effort: "light", minimum_age: 16,
    accessibility: "Some uneven stream-bank terrain.", safety_notes: "Wear sturdy waterproof footwear.", capacity: 12, requires_waiver: true, confirmed_count: 7,
    image_url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85",
    status: "published", version: 1, organisation_name: "GTA Watershed Watch",
    location_label: "East York, Toronto", address_line: "550 Bayview Avenue", locality: "East York", city: "Toronto", postcode: "M4W 3X8", country_code: "CA", latitude: 43.6841, longitude: -79.3654, location_visibility: "public",
    causes: [causes[2]!], distance_km: 3.4, is_saved: false,
  },
  {
    ...requirementDefaults,
    id: "hutt-planting", title: "Credit River Native Planting",
    description: "Restore a riverbank corridor with native plants and local conservation guides.",
    impact_statement: "Create healthier habitat along the Credit River.", tasks: "Prepare planting sites, place native seedlings, and spread mulch.",
    meeting_point: "Erindale Park main entrance", starts_at: future(14), ends_at: future(14), recurrence: "monthly", effort: "active", minimum_age: 14,
    accessibility: "Mostly level grass with adaptable planting tasks.", safety_notes: "Closed shoes and weatherproof layers recommended.", capacity: 30, requires_waiver: true, confirmed_count: 12,
    image_url: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=85", status: "published", version: 1, organisation_name: "Credit Valley Green Team",
    location_label: "Mississauga, Ontario", address_line: "1695 Dundas Street West", locality: "Mississauga", city: "Mississauga", postcode: "L5C 1E3", country_code: "CA", latitude: 43.5499, longitude: -79.6627, location_visibility: "public",
    causes: [causes[1]!], distance_km: 14.2, is_saved: false,
  },
  {
    ...requirementDefaults,
    application_mode: "external",
    external_application_url: "https://example.org/volunteer/food-rescue",
    listing_source: "Toronto Food Share Collective website",
    listing_source_url: "https://example.org/volunteer/food-rescue",
    listing_verification_status: "pending",
    id: "porirua-food-rescue", title: "North York Food Rescue Sort",
    description: "Sort rescued groceries into family food parcels with an experienced community team.",
    impact_statement: "Keep good food out of landfill and support families across North York.", tasks: "Check produce, assemble parcels, label dietary needs, and tidy the workspace.",
    meeting_point: "Community hub reception", starts_at: future(17), ends_at: future(17), recurrence: "weekly", effort: "light", minimum_age: 16,
    accessibility: "Step-free indoor workspace.", safety_notes: "Food-safe gloves and training are provided.", capacity: 16, requires_waiver: true, confirmed_count: 6,
    image_url: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1200&q=85", status: "published", version: 1, organisation_name: "Toronto Food Share Collective",
    location_label: "North York, Toronto", address_line: "5100 Yonge Street", locality: "North York", city: "Toronto", postcode: "M2N 5V7", country_code: "CA", latitude: 43.7686, longitude: -79.4126, location_visibility: "public",
    causes: [causes[3]!], distance_km: 17.7, is_saved: false,
  },
  {
    ...requirementDefaults,
    id: "high-park-pollinators", title: "High Park Pollinator Count",
    description: "Join a guided citizen-science walk to count bees, butterflies, and flowering plants.",
    impact_statement: "Create a snapshot of pollinator health in one of Toronto’s largest parks.", tasks: "Walk a marked route, photograph pollinators, and record observations on a provided sheet.",
    meeting_point: "High Park Nature Centre entrance", starts_at: future(4), ends_at: future(4), recurrence: "one_off", effort: "light", minimum_age: 12,
    accessibility: "Paved route with frequent rest points; seated counting is available.", safety_notes: "Bring water and sun protection.", capacity: 20, requires_waiver: true, confirmed_count: 9,
    image_url: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=1200&q=85", status: "published", version: 1, organisation_name: "Toronto Community Action Network",
    location_label: "High Park, Toronto", address_line: "375 Colborne Lodge Drive", locality: "High Park", city: "Toronto", postcode: "M6R 2Z3", country_code: "CA", latitude: 43.6465, longitude: -79.4637, location_visibility: "public",
    time_commitment_minutes: 60, causes: [causes[2]!], distance_km: 6.6, is_saved: false,
  },
  {
    ...requirementDefaults,
    id: "scarborough-conversation", title: "Scarborough Newcomer Conversation Club",
    description: "Support newcomers practising conversational English in a welcoming small-group setting.",
    impact_statement: "Help new neighbours build confidence and community connections.", tasks: "Facilitate conversation prompts, welcome participants, and prepare learning materials.",
    meeting_point: "Scarborough Civic Centre library entrance", starts_at: future(6), ends_at: future(6), recurrence: "weekly", effort: "light", minimum_age: 18,
    accessibility: "Step-free indoor venue with accessible washrooms.", safety_notes: "Follow library volunteer guidelines.", capacity: 10, requires_waiver: true, confirmed_count: 5,
    screening_required: true, screening_steps: "A brief reference check and volunteer orientation are required.", time_commitment_minutes: 120,
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=85", status: "published", version: 1, organisation_name: "Scarborough Welcome Collective",
    location_label: "Scarborough, Toronto", address_line: "150 Borough Drive", locality: "Scarborough", city: "Toronto", postcode: "M1P 4N7", country_code: "CA", latitude: 43.7739, longitude: -79.2577, location_visibility: "public",
    causes: [causes[3]!], distance_km: 18.1, is_saved: true,
  },
  {
    ...requirementDefaults,
    id: "etobicoke-tech-help", title: "Etobicoke Seniors Tech Help",
    description: "Offer patient one-to-one support with phones, tablets, video calls, and online services.",
    impact_statement: "Help older adults stay connected and confident online.", tasks: "Answer basic device questions, demonstrate accessibility settings, and share safety tips.",
    meeting_point: "Etobicoke Civic Centre reception", starts_at: future(9), ends_at: future(9), recurrence: "monthly", effort: "light", minimum_age: 16,
    accessibility: "Fully accessible indoor venue; quiet workstations are available.", safety_notes: "Never request or record a participant’s passwords.", capacity: 8, requires_waiver: true, confirmed_count: 4,
    training_required: true, training_commitment: "Complete a 30-minute digital-safety orientation online.", time_commitment_minutes: 90,
    image_url: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=85", status: "published", version: 1, organisation_name: "Etobicoke Seniors Connect",
    location_label: "Etobicoke, Toronto", address_line: "399 The West Mall", locality: "Etobicoke", city: "Toronto", postcode: "M9C 2Y2", country_code: "CA", latitude: 43.6432, longitude: -79.5657, location_visibility: "public",
    causes: [causes[3]!], distance_km: 14.8, is_saved: false,
  },
  {
    ...requirementDefaults,
    id: "rouge-restoration", title: "Rouge Valley Trail Restoration",
    description: "Work with a conservation crew to restore a worn trail edge and protect native habitat.",
    impact_statement: "Reduce erosion and help visitors enjoy the Rouge responsibly.", tasks: "Move mulch, install trail markers, remove invasive plants, and clear light debris.",
    meeting_point: "Rouge Valley Conservation Centre parking area", starts_at: future(12), ends_at: future(12), recurrence: "one_off", effort: "active", minimum_age: 16,
    is_accessible: false, accessibility: "Uneven natural terrain with slopes and no step-free task area.", safety_notes: "Sturdy boots, long pants, and gloves are required.", capacity: 28, requires_waiver: true, confirmed_count: 13,
    time_commitment_minutes: 240, image_url: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=85", status: "published", version: 1, organisation_name: "Rouge Conservation Crew",
    location_label: "Scarborough, Greater Toronto Area", address_line: "1749 Meadowvale Road", locality: "Scarborough", city: "Toronto", postcode: "M1B 5W8", country_code: "CA", latitude: 43.8177, longitude: -79.1717, location_visibility: "public",
    causes: [causes[1]!], distance_km: 28.4, is_saved: false,
  },
  {
    ...requirementDefaults,
    application_mode: "external", external_application_url: "https://example.org/volunteer/brampton-cleanup", listing_source: "Brampton Neighbourhood Green Team website", listing_source_url: "https://example.org/volunteer/brampton-cleanup", listing_verification_status: "pending",
    id: "brampton-cleanup", title: "Brampton Park Cleanup Sprint",
    description: "Take part in a focused neighbourhood cleanup around trails, play areas, and picnic spaces.",
    impact_statement: "Make a busy community park cleaner in just ninety minutes.", tasks: "Collect litter, separate recyclables, and report bulky waste to the event lead.",
    meeting_point: "Chinguacousy Park greenhouse entrance", starts_at: future(15), ends_at: future(15), recurrence: "monthly", effort: "moderate", minimum_age: 14,
    accessibility: "Paved cleanup zone and lightweight grabbers are available.", safety_notes: "Wear closed shoes; gloves and grabbers are supplied.", capacity: 40, requires_waiver: true, confirmed_count: 19,
    time_commitment_minutes: 90, image_url: "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=1200&q=85", status: "published", version: 1, organisation_name: "Brampton Neighbourhood Green Team",
    location_label: "Brampton, Greater Toronto Area", address_line: "9050 Bramalea Road", locality: "Brampton", city: "Brampton", postcode: "L6S 6G7", country_code: "CA", latitude: 43.7284, longitude: -79.7258, location_visibility: "public",
    causes: [causes[0]!], distance_km: 28.6, is_saved: false,
  },
  {
    ...requirementDefaults,
    id: "markham-tree-care", title: "Markham Young Tree Care Day",
    description: "Help recently planted street trees survive summer heat with hands-on care.",
    impact_statement: "Give young urban trees a stronger start across Markham.", tasks: "Water trees, refresh mulch rings, inspect guards, and record damaged stakes.",
    meeting_point: "Markham Civic Centre flagpoles", starts_at: future(18), ends_at: future(18), recurrence: "monthly", effort: "active", minimum_age: 16,
    is_accessible: false, accessibility: "Work takes place on grass boulevards with uneven surfaces.", safety_notes: "Closed footwear and sun protection are required.", capacity: 22, requires_waiver: true, confirmed_count: 8,
    training_required: true, training_commitment: "Attend a 45-minute tool and tree-care briefing before starting.", time_commitment_minutes: 180,
    image_url: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=1200&q=85", status: "published", version: 1, organisation_name: "Markham Urban Forest Team",
    location_label: "Markham, Greater Toronto Area", address_line: "101 Town Centre Boulevard", locality: "Markham", city: "Markham", postcode: "L3R 9W3", country_code: "CA", latitude: 43.8561, longitude: -79.337, location_visibility: "public",
    causes: [causes[1]!], distance_km: 23.1, is_saved: false,
  },
  {
    ...requirementDefaults,
    id: "youth-meal-kits", title: "Downtown Youth Meal Kit Packing",
    description: "Pack shelf-stable meal kits for youth outreach programs in a fast-moving team shift.",
    impact_statement: "Prepare practical food support for young people across downtown Toronto.", tasks: "Check expiry dates, assemble meal kits, label boxes, and reset packing stations.",
    meeting_point: "Community warehouse volunteer desk", starts_at: future(21), ends_at: future(21), recurrence: "weekly", effort: "moderate", minimum_age: 18,
    accessibility: "Step-free warehouse floor with seated packing tasks on request.", safety_notes: "Food-safe gloves and a safety briefing are provided.", capacity: 14, requires_waiver: true, confirmed_count: 10,
    screening_required: true, screening_steps: "Complete an online vulnerable-sector screening form before confirmation.", time_commitment_minutes: 120,
    image_url: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1200&q=85", status: "published", version: 1, organisation_name: "Toronto Youth Outreach Kitchen",
    location_label: "Roncesvalles, Toronto", address_line: "50 Wabash Avenue", locality: "Roncesvalles", city: "Toronto", postcode: "M6R 1N2", country_code: "CA", latitude: 43.6537, longitude: -79.4442, location_visibility: "public",
    causes: [causes[3]!], distance_km: 4.9, is_saved: false,
  },
];
export const profileFor = (role: "volunteer" | "organiser"): Profile => ({
  id: role === "volunteer" ? "00000000-0000-4000-8000-000000000020" : "00000000-0000-4000-8000-000000000010",
  role, display_name: role === "volunteer" ? "Mia Thompson" : "Toronto Community Action Network",
  email: `${role}@example.com`, search_location_label: "Downtown Toronto, Ontario", search_latitude: 43.6532, search_longitude: -79.3832, search_radius_km: 50, theme: "system",
  organisation_name: role === "organiser" ? "Toronto Community Action Network" : null,
});
export const applications: Application[] = [
  { id: "application-1", opportunity_id: opportunities[0]!.id, opportunity_title: opportunities[0]!.title,
    volunteer_id: profileFor("volunteer").id, volunteer_name: "Mia Thompson", volunteer_email: "volunteer@example.com",
    note: "I care about the coast and can help for the full morning.", experience: "Two previous community cleanups.", availability: "Available for the full event",
    status: "received", version: 1, next_step: "Your application was received. The host will review it next.", history: [],
    waiver: { signed_name: "Mia Thompson", is_minor: false, guardian_name: null, guardian_email: null, guardian_relationship: null, accepted_at: new Date().toISOString(), waiver_version: 1, waiver_title: "GiveHub volunteer agreement" } },
];
