/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#F6F6F0",
        foreground: "#17221A",
        card: "#FFFEFA",
        border: "#E8E8E2",
        primary: "#2A8D58",
        "primary-foreground": "#F8FFF8",
        secondary: "#E4F0E4",
        "secondary-foreground": "#236C45",
        muted: "#ECEDE6",
        "muted-foreground": "#657166",
        accent: "#BB704B",
        destructive: "#E03030",
        input: "#EEF1EA",
        "dark-background": "#101A14",
        "dark-foreground": "#EDF4EC",
        "dark-card": "#17241C",
        "dark-border": "#2B372F",
        "dark-primary": "#8BD19F",
        "dark-primary-foreground": "#0C1810",
        "dark-secondary": "#1A3022",
        "dark-secondary-foreground": "#A0DCAF",
        "dark-muted": "#1E2B22",
        "dark-muted-foreground": "#9BAC9F",
        "dark-accent": "#E3A37E",
        "dark-destructive": "#FF5E6A",
        // Compatibility aliases while the remaining screens migrate to semantic tokens.
        ink: "#17221A",
        paper: "#F6F6F0",
        moss: "#2A8D58",
        fern: "#E4F0E4",
        clay: "#BB704B",
        night: "#101A14",
        mist: "#ECEDE6",
      },
      fontFamily: {
        display: ["LibreBaskerville_700Bold"],
        sans: ["DMSans_400Regular"],
        medium: ["DMSans_600SemiBold"],
        strong: ["DMSans_700Bold"],
        mono: ["DMMono_500Medium"],
      },
      borderRadius: { card: "16px", feature: "24px" },
    },
  },
  plugins: [],
};

